name: Node.js Package

# Trigger workflow when a GitHub release is created
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v4

      # Setup Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - run: npm ci

      # Run tests
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checkout the repo again
      - uses: actions/checkout@v4

      # Setup Node.js and GitHub Packages registry
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      # Install dependencies
      - run: npm ci

      # Publish package to GitHub Packages
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

